spring.application.name=redirect-url-api
server.port=8080

### DATABASE
spring.datasource.url=jdbc:postgresql://${DATABASE_APPLICATION_URL:localhost}:5432/${DATABASE_NAME:shorten-url}
spring.datasource.username= ${DATABASE_USERNAME:postgres}
spring.datasource.password= ${DATABASE_PASSWORD:postgres}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none


# Desabilitar HTTPS
server.ssl.enabled=false

springdoc.swagger-ui.path=/swagger